DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS film_mpa;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS film_likes;
DROP TABLE IF EXISTS friend_request;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS app_user;

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    login VARCHAR(255),
    name VARCHAR(255),
    birthday DATE,
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS film (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    rate INTEGER NOT NULL,
    CONSTRAINT check_duration_positive CHECK (duration > 0),
    CONSTRAINT check_release_date CHECK (release_date >= DATE '1895-12-28')
);

CREATE TABLE IF NOT EXISTS friends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    CONSTRAINT fk_user_id_friends FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_friend_id_friends FOREIGN KEY (friend_id) REFERENCES app_user(id),
    CONSTRAINT unique_friend_pair UNIQUE (user_id, friend_id),
    CONSTRAINT check_not_self_friend CHECK (user_id <> friend_id)
);

CREATE TABLE IF NOT EXISTS friend_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    friend_id_request BIGINT NOT NULL,
    CONSTRAINT fk_user_id_friend_request FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_friend_id_friend_request FOREIGN KEY (friend_id_request) REFERENCES app_user(id),
    CONSTRAINT unique_request_pair UNIQUE (user_id, friend_id_request),
    CONSTRAINT check_not_self_request CHECK (user_id <> friend_id_request)
);

CREATE TABLE IF NOT EXISTS film_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_film_id_likes FOREIGN KEY (film_id) REFERENCES film(id),
    CONSTRAINT fk_user_id_likes FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT unique_user_like UNIQUE (user_id, film_id)
);
CREATE INDEX IF NOT EXISTS idx_film_likes_film_id ON film_likes(film_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_user_id ON film_likes(user_id);

CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT genre_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS film_genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT fk_fg_film_id FOREIGN KEY (film_id) REFERENCES film(id),
    CONSTRAINT fk_fg_genre_id FOREIGN KEY (genre_id) REFERENCES genre(id),
    CONSTRAINT unique_film_genre UNIQUE (film_id, genre_id)
);
CREATE INDEX IF NOT EXISTS idx_film_genre_film_id ON film_genre(film_id);
CREATE INDEX IF NOT EXISTS idx_film_genre_genre_id ON film_genre(genre_id);

CREATE TABLE IF NOT EXISTS mpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name VARCHAR(50) NOT NULL,
    CONSTRAINT unique_mpa_name UNIQUE (mpa_name)
);

CREATE TABLE IF NOT EXISTS film_mpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL,
    mpa_id BIGINT NOT NULL,
    CONSTRAINT fk_film_mpa_film FOREIGN KEY (film_id) REFERENCES film(id),
    CONSTRAINT fk_film_mpa_mpa FOREIGN KEY (mpa_id) REFERENCES mpa(id),
    CONSTRAINT unique_film_mpa UNIQUE(film_id, mpa_id)
);

CREATE INDEX IF NOT EXISTS idx_film_mpa_film_id ON film_mpa(film_id);
CREATE INDEX IF NOT EXISTS idx_film_mpa_mpa_id ON film_mpa(mpa_id);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    review_text TEXT NOT NULL,
    CONSTRAINT fk_user_id_reviews FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_film_id_reviews FOREIGN KEY (film_id) REFERENCES film(id),
    CONSTRAINT unique_user_film_reviews UNIQUE (user_id, film_id)
);




